language: C++
sudo: required
dist: bionic
compiler: g++

install:
    - source ci/travis/install-linux.sh

script:
    - mkdir build
    - cd build
    - cmake -GNinja ..
    - ninja
    - cd ../test
    - mkdir build
    - cd build
    - cmake -GNinja ..
    - ninja
    - ./TestDynSys
