language: C++
sudo: required
dist: xenial
compiler: g++

install:
    - source ci/travis/install-linux.sh

before_script:
    - QTDIR="/opt/qt57"
    - PATH="$QTDIR/bin:$PATH"
    - source /opt/qt57/bin/qt57-env.sh

script:
    - mkdir build
    - cd build
    - cmake -GNinja ..
    - ninja
